sonar.projectKey=R-Christina_MS6
sonar.organization=r-christina
sonar.projectName=MS6
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=reports/coverage.xml

sonar.coverage.exclusions=tests/**